#!/bin/bash
cd "$( dirname "${BASH_SOURCE[0]}" )"
while true
do
	git pull
	chromium-browser --user-data-dir="/tmp/chromium-user-data-`date +%s`" --disable-web-security --app=file://`pwd`/OpenPRs.html
	rm -rf /tmp/chromium-user-data-*
done
